keys:
  - &nlaptop age108xqmsshksap8695ewy48pfdhw7kx5k9dgp8pxzx5tqdwlu6naksweyfc3
  - &node1 age1sfwzafxl2r3n24n50rv962l00n9jsx6gw2gjrxs0u2286ue9dq9sljv9lz
  - &node2 age15dhh0jqrajgxhyl45ly8vesru5fh606vwu9nclppu3wpw06zj9zqv6kp9x
  - &node3 age1quqcrstuzsd8cc9ed9h803ghvdqg6xynvqv23rnreufsvcrvdacqps0mwf
  - &node4 age129y5rmhh6lg7npch60qttcrhu03gv696cs5hs5svkqdm5eafwdpqndsnup
  - &node5 age1hd3svmmqswnf5anzxc8x6h4uhqwu5q9wmdcw3lvgm97g8naq9d7qk6kwfj
creation_rules:
  - path_regex: secrets/.*\.yaml
    key_groups:
      - age:
        - *nlaptop
        - *node1
        - *node2
        - *node3
        - *node4
        - *node5
