keys:
  - &nlaptop age108xqmsshksap8695ewy48pfdhw7kx5k9dgp8pxzx5tqdwlu6naksweyfc3
  - &node0 age18lu79lcspn67c05zmglt5036jh6d270nhne76t4e3u64wwu8qejsdyk4k6
  - &node1 age17fljhj2fkjw2cjvymq22494a3t3chqtj3evhwn0rxwz0vke3sd0qzq2c2h
  - &node2 age1xneuqq7x7aq5ftv2vzs58vz2ch33sczdnpzyj6jk9c29s3w6743ssncllu
  - &node3 age1rvf2hzwqlqq9ff8v24rgxuunmtus23yry22xzxsktzfc27sl8d2sg9glaf
creation_rules:
  - path_regex: secrets/.*\.yaml
    key_groups:
      - age:
        - *nlaptop
        - *node0
        - *node1
        - *node2
        - *node3
