keys:
  - &nlaptop age108xqmsshksap8695ewy48pfdhw7kx5k9dgp8pxzx5tqdwlu6naksweyfc3
  - &node1 age18lu79lcspn67c05zmglt5036jh6d270nhne76t4e3u64wwu8qejsdyk4k6
creation_rules:
  - path_regex: secrets/.*\.yaml
    key_groups:
      - age:
        - *nlaptop
        - *node1
