keys:
  - &nlaptop age108xqmsshksap8695ewy48pfdhw7kx5k9dgp8pxzx5tqdwlu6naksweyfc3
  - &node0 age18lu79lcspn67c05zmglt5036jh6d270nhne76t4e3u64wwu8qejsdyk4k6
  - &node1 age17fljhj2fkjw2cjvymq22494a3t3chqtj3evhwn0rxwz0vke3sd0qzq2c2h
  - &node2 age1xneuqq7x7aq5ftv2vzs58vz2ch33sczdnpzyj6jk9c29s3w6743ssncllu
  - &node3 age1rvf2hzwqlqq9ff8v24rgxuunmtus23yry22xzxsktzfc27sl8d2sg9glaf
  - &node4 age1mtngej5qtyh36gahn5m3zs0ryd99yt2r276ayvs2exc8zysrvcyquj84nz
  - &node5 age1a4egwvg4r0fh0hemxr4kna533q8scyy9m2az3lphk687m2ez23kqjjlc8q
  - &node6 age198s6g2t0e4xf653y4u8cgaq4ks6z83vrurlvc543t72jpvgmjsnq7yz6lv
  - &node7 age15a9jvj9zmxjncm7cps9gz82untnnn66grzwwkpvvztyz6ddeuf4sltc4q7
  - &node8 age1rzm3wqrapmntctecxs4pw3298f2y37jq4jxkxla86g5eef4hjyus2f3ff2
  - &node9 age1ljqd46aajetrmwum2pljn2vjpa7aa7jxewd2m7xye758ypasg3nsv2hcgq
  - &node10 age12c4tynv5rp5fcfllggy4xlaustjjtl4qwzlcvp85g8j625m0kq3syadnk4
creation_rules:
  - path_regex: secrets/.*\.yaml
    key_groups:
      - age:
        - *nlaptop
        - *node0
        - *node1
        - *node2
        - *node3
        - *node4
        - *node5
        - *node6
        - *node7
        - *node8
        - *node9
        - *node10
