slurmImage: ghcr.io/stackhpc/slurm-docker-cluster:1f51003

login:
  # Deployment resource name
  name: login
  replicas: 1

slurmd:
  # StatefulSet resource name
  name: slurmd # NB this must match NodeName= in slurm-cluster-chart/files/slurm.conf
  replicas: 2

slurmctld:
  name: slurmctld

storage:
  mountPath: /home
  persistentVolumeClaim:
    enabled: true
  rooknfs.enabled: false
  storageClassName: slurm-rook-nfs
  # Name for the R-W-M volume to provision
  claimName: slurm-shared-storage
  # Capacite of the R-W-M volume
  capacity: 10Gi

# Values for Slurm's database container
database:
  image: mariadb:10.10
  storage: 100Mi

# Configmap resource names
configmaps:
  slurmConf: slurm-conf-configmap
  slurmdbdConf: slurmdbd-conf-configmap
  sshdConfig: sshd-config-configmap

# Public key used for ssh access to the login node
# If let undefined, assumes you have run the provided publish-keys.sh script to publish your public key prior to deployment
sshPublicKey:

# Secret resource names
secrets:
  mungeKey: munge-key-secret

openOnDemand:
  #Password for default Open OnDemand user 'rocky'
  password: password
