repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: k8s-ssh-bastion
    url: https://nefelim4ag.github.io/k8s-ssh-bastion/
  - name: uptime-kuma
    url: https://helm.irsigler.cloud
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/
  - name: obeone
    url: https://charts.obeone.cloud

releases:
  # Distributed storage
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.7.1
    values:
      - ./values/longhorn.yaml
  # Load balancer
  - name: metallb
    namespace: metallb-system
    chart: metallb/metallb
    version: 0.14.5
  # Ingress for local network
  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.11.2
    values:
      - ./values/nginx-internal.yaml
  # SSH Jumpbox
  - name: jumpbox
    namespace: jumpbox-system
    chart: k8s-ssh-bastion/k8s-ssh-bastion
    version: 0.5.4
    values:
      - ./values/jumpbox.yaml
  # Technitium DNS
  - name: technitium-dns
    namespace: technitium-dns
    chart: obeone/technitium-dnsserver
    version: 1.2.1
    values:
      - ./values/technitium-dns.yaml
  # Uptime Kuma
  - name: uptime-kuma
    namespace: monitoring
    chart: uptime-kuma/uptime-kuma
    version: 2.20.0
    values:
      - ./values/uptime-kuma.yaml
  # Kubernetes Dashboard
  - name: kubernetes-dashboard
    namespace: monitoring
    chart: kubernetes-dashboard/kubernetes-dashboard
    version: 7.8.0
